USE [CHCPIS]
GO

/****** Object:  Index [IX_BsPatient]    Script Date: 2017/3/28 10:21:27 ******/
CREATE NONCLUSTERED INDEX [IX_BsPatient] ON [dbo].[BsPatient]
(
	[InPatNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO